# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.products_api import ProductsApi  # noqa: E501
from qu.crm.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_product_version(self):
        """Test case for create_product_version

        Create new product version  # noqa: E501
        """
        pass

    def test_delete_product_version(self):
        """Test case for delete_product_version

        Delete product version  # noqa: E501
        """
        pass

    def test_get_all_product_available_versions(self):
        """Test case for get_all_product_available_versions

        Product available versions  # noqa: E501
        """
        pass

    def test_get_product(self):
        """Test case for get_product

        Product  # noqa: E501
        """
        pass

    def test_get_product_version(self):
        """Test case for get_product_version

        Product version  # noqa: E501
        """
        pass

    def test_get_product_versions(self):
        """Test case for get_product_versions

        Product versions  # noqa: E501
        """
        pass

    def test_get_products(self):
        """Test case for get_products

        Products list  # noqa: E501
        """
        pass

    def test_mark_product_version_for_deletion(self):
        """Test case for mark_product_version_for_deletion

        Mark product version for deletion  # noqa: E501
        """
        pass

    def test_update_product_version(self):
        """Test case for update_product_version

        Update product version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
