# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.reseller_api import ResellerApi  # noqa: E501
from qu.crm.rest import ApiException


class TestResellerApi(unittest.TestCase):
    """ResellerApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.reseller_api.ResellerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reseller_billed_periods(self):
        """Test case for get_reseller_billed_periods

        Reseller subscription billed period list  # noqa: E501
        """
        pass

    def test_get_reseller_invoices(self):
        """Test case for get_reseller_invoices

        Reseller invoice list  # noqa: E501
        """
        pass

    def test_get_reseller_subscription(self):
        """Test case for get_reseller_subscription

        Get reseller subscription  # noqa: E501
        """
        pass

    def test_get_reseller_subscription_usage(self):
        """Test case for get_reseller_subscription_usage

        Get reseller subscription usage  # noqa: E501
        """
        pass

    def test_get_reseller_subscriptions(self):
        """Test case for get_reseller_subscriptions

        Get reseller subscriptions  # noqa: E501
        """
        pass

    def test_reseller_change_plan(self):
        """Test case for reseller_change_plan

        Change plan  # noqa: E501
        """
        pass

    def test_reseller_signup(self):
        """Test case for reseller_signup

        Create reseller subscription  # noqa: E501
        """
        pass

    def test_suspend_reseller_subscription(self):
        """Test case for suspend_reseller_subscription

        Suspend reseller subscription  # noqa: E501
        """
        pass

    def test_unsuspend_reseller_subscription(self):
        """Test case for unsuspend_reseller_subscription

        Unsuspend reseller subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
