# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.dev_api import DevApi  # noqa: E501
from qu.crm.rest import ApiException


class TestDevApi(unittest.TestCase):
    """DevApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.dev_api.DevApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dev_create_subscription(self):
        """Test case for dev_create_subscription

        Create dev subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
