# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import qu.crm
from qu.crm.models.period_pricing import PeriodPricing  # noqa: E501
from qu.crm.rest import ApiException

class TestPeriodPricing(unittest.TestCase):
    """PeriodPricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PeriodPricing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeriodPricing`
        """
        model = qu.crm.models.period_pricing.PeriodPricing()  # noqa: E501
        if include_optional :
            return PeriodPricing(
                name = '1m', 
                metrics = [
                    qu.crm.models.billing_metric.BillingMetric(
                        name = '', 
                        amount_in_price = 56, 
                        limit = 56, 
                        unit_price = 1.337, 
                        unit_size = 56, )
                    ], 
                base_price = 56
            )
        else :
            return PeriodPricing(
        )
        """

    def testPeriodPricing(self):
        """Test PeriodPricing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
