# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.subscriptions_api import SubscriptionsApi  # noqa: E501
from qu.crm.rest import ApiException


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.subscriptions_api.SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_free_addons(self):
        """Test case for add_free_addons

        Add free addons  # noqa: E501
        """
        pass

    def test_aet_account_manager(self):
        """Test case for aet_account_manager

        Assign account manager  # noqa: E501
        """
        pass

    def test_agree_with_request_billing(self):
        """Test case for agree_with_request_billing

        PAP agree with additional billing  # noqa: E501
        """
        pass

    def test_change_addons(self):
        """Test case for change_addons

        Addon change  # noqa: E501
        """
        pass

    def test_change_plan(self):
        """Test case for change_plan

        Change plan  # noqa: E501
        """
        pass

    def test_check_domain(self):
        """Test case for check_domain

        Domain availability  # noqa: E501
        """
        pass

    def test_clear_last_payment_fail(self):
        """Test case for clear_last_payment_fail

        Clear last payment fail  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete subscription  # noqa: E501
        """
        pass

    def test_extend_validity(self):
        """Test case for extend_validity

        Extends account validity  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Account  # noqa: E501
        """
        pass

    def test_get_account_manager(self):
        """Test case for get_account_manager

        Get account manager  # noqa: E501
        """
        pass

    def test_get_active_addons(self):
        """Test case for get_active_addons

        Addon list  # noqa: E501
        """
        pass

    def test_get_billing_info(self):
        """Test case for get_billing_info

        Billing info  # noqa: E501
        """
        pass

    def test_get_billing_metrics(self):
        """Test case for get_billing_metrics

        Billing metrics  # noqa: E501
        """
        pass

    def test_get_billing_status(self):
        """Test case for get_billing_status

        Billing status  # noqa: E501
        """
        pass

    def test_get_domain_info(self):
        """Test case for get_domain_info

        Domain info  # noqa: E501
        """
        pass

    def test_get_failed_payment(self):
        """Test case for get_failed_payment

        Failed payment  # noqa: E501
        """
        pass

    def test_get_failed_payments(self):
        """Test case for get_failed_payments

        Failed payment list  # noqa: E501
        """
        pass

    def test_get_install_progress(self):
        """Test case for get_install_progress

        Install progress  # noqa: E501
        """
        pass

    def test_get_note(self):
        """Test case for get_note

        Note  # noqa: E501
        """
        pass

    def test_get_payment_method(self):
        """Test case for get_payment_method

        Payment method  # noqa: E501
        """
        pass

    def test_get_payment_processor(self):
        """Test case for get_payment_processor

        Payment processor  # noqa: E501
        """
        pass

    def test_get_source(self):
        """Test case for get_source

        Install source  # noqa: E501
        """
        pass

    def test_get_subscription(self):
        """Test case for get_subscription

        Subscription  # noqa: E501
        """
        pass

    def test_get_subscription_attributes(self):
        """Test case for get_subscription_attributes

        Subscription attribute list  # noqa: E501
        """
        pass

    def test_get_subscription_discounts(self):
        """Test case for get_subscription_discounts

        Subscription discounts  # noqa: E501
        """
        pass

    def test_get_subscription_invoices(self):
        """Test case for get_subscription_invoices

        Subscription invoice list  # noqa: E501
        """
        pass

    def test_get_subscriptions(self):
        """Test case for get_subscriptions

        Subscription list  # noqa: E501
        """
        pass

    def test_get_upgrade_variations(self):
        """Test case for get_upgrade_variations

        Upgrade variation list  # noqa: E501
        """
        pass

    def test_is_additional_billing_agreed(self):
        """Test case for is_additional_billing_agreed

        PAP get additional billing  # noqa: E501
        """
        pass

    def test_refresh_account(self):
        """Test case for refresh_account

        Refresh account  # noqa: E501
        """
        pass

    def test_remove_lock(self):
        """Test case for remove_lock

        Remove lock  # noqa: E501
        """
        pass

    def test_resume_billing(self):
        """Test case for resume_billing

        Restart billing  # noqa: E501
        """
        pass

    def test_set_billing_info(self):
        """Test case for set_billing_info

        Billing info  # noqa: E501
        """
        pass

    def test_set_custom_domain(self):
        """Test case for set_custom_domain

        Custom domain  # noqa: E501
        """
        pass

    def test_set_default_domain(self):
        """Test case for set_default_domain

        Default domain  # noqa: E501
        """
        pass

    def test_set_domain(self):
        """Test case for set_domain

        Custom domain  # noqa: E501
        """
        pass

    def test_set_lock(self):
        """Test case for set_lock

        Set subscription lock  # noqa: E501
        """
        pass

    def test_set_note(self):
        """Test case for set_note

        Note  # noqa: E501
        """
        pass

    def test_set_owner_email(self):
        """Test case for set_owner_email

        Owner's email  # noqa: E501
        """
        pass

    def test_set_pap_tracking_params(self):
        """Test case for set_pap_tracking_params

        PAP tracking params  # noqa: E501
        """
        pass

    def test_set_payment_method(self):
        """Test case for set_payment_method

        Payment method  # noqa: E501
        """
        pass

    def test_set_source(self):
        """Test case for set_source

        Install source  # noqa: E501
        """
        pass

    def test_set_subscription_usage(self):
        """Test case for set_subscription_usage

        Subscription usage  # noqa: E501
        """
        pass

    def test_set_update_policy(self):
        """Test case for set_update_policy

        Set update policy  # noqa: E501
        """
        pass

    def test_signup(self):
        """Test case for signup

        Create subscription  # noqa: E501
        """
        pass

    def test_stop_billing(self):
        """Test case for stop_billing

        Stop billing  # noqa: E501
        """
        pass

    def test_suspend(self):
        """Test case for suspend

        Suspend subscription  # noqa: E501
        """
        pass

    def test_terminate(self):
        """Test case for terminate

        Terminate subscription  # noqa: E501
        """
        pass

    def test_unsuspend(self):
        """Test case for unsuspend

        Unsuspend subscription  # noqa: E501
        """
        pass

    def test_update_application(self):
        """Test case for update_application

        Update subscription  # noqa: E501
        """
        pass

    def test_validate_billing_info(self):
        """Test case for validate_billing_info

        Test Billing info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
