# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.templates_api import TemplatesApi  # noqa: E501
from qu.crm.rest import ApiException


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.templates_api.TemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_template(self):
        """Test case for get_template

        Template  # noqa: E501
        """
        pass

    def test_get_templates(self):
        """Test case for get_templates

        Template list  # noqa: E501
        """
        pass

    def test_update_template(self):
        """Test case for update_template

        Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
