# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.my_account_api import MyAccountApi  # noqa: E501
from qu.crm.rest import ApiException


class TestMyAccountApi(unittest.TestCase):
    """MyAccountApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.my_account_api.MyAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_stop(self):
        """Test case for cancel_stop

        Restart billing  # noqa: E501
        """
        pass

    def test_change_addons_for_my_account(self):
        """Test case for change_addons_for_my_account

        Addon change  # noqa: E501
        """
        pass

    def test_download_invoice_for_my_account(self):
        """Test case for download_invoice_for_my_account

        Download invoice  # noqa: E501
        """
        pass

    def test_download_summary(self):
        """Test case for download_summary

        Downloads summary  # noqa: E501
        """
        pass

    def test_generate(self):
        """Test case for generate

        'My Account' token  # noqa: E501
        """
        pass

    def test_get_account_invoices(self):
        """Test case for get_account_invoices

        Invoices list  # noqa: E501
        """
        pass

    def test_get_account_summaries(self):
        """Test case for get_account_summaries

        Summaries list  # noqa: E501
        """
        pass

    def test_get_active_addons_for_my_account(self):
        """Test case for get_active_addons_for_my_account

        Plan addons list  # noqa: E501
        """
        pass

    def test_get_agents_count(self):
        """Test case for get_agents_count

        Agents count  # noqa: E501
        """
        pass

    def test_get_all_variation_addons_for_my_account(self):
        """Test case for get_all_variation_addons_for_my_account

        Variations addons  # noqa: E501
        """
        pass

    def test_get_billing_info_for_my_account(self):
        """Test case for get_billing_info_for_my_account

        Billing info  # noqa: E501
        """
        pass

    def test_get_billing_status_for_my_account(self):
        """Test case for get_billing_status_for_my_account

        Billing status  # noqa: E501
        """
        pass

    def test_get_coupon_for_my_account(self):
        """Test case for get_coupon_for_my_account

        Coupon  # noqa: E501
        """
        pass

    def test_get_knowledgebases_count(self):
        """Test case for get_knowledgebases_count

        Knowledgebases count  # noqa: E501
        """
        pass

    def test_get_payment_method_for_my_account(self):
        """Test case for get_payment_method_for_my_account

        Get Payment method  # noqa: E501
        """
        pass

    def test_get_payment_processor_for_my_account(self):
        """Test case for get_payment_processor_for_my_account

        Payment processor  # noqa: E501
        """
        pass

    def test_get_subscription_for_my_account(self):
        """Test case for get_subscription_for_my_account

        Subscription  # noqa: E501
        """
        pass

    def test_get_summary_for_my_account(self):
        """Test case for get_summary_for_my_account

        Current period summary  # noqa: E501
        """
        pass

    def test_get_upgrade_variations_for_my_account(self):
        """Test case for get_upgrade_variations_for_my_account

        Upgrade variation list  # noqa: E501
        """
        pass

    def test_get_variation_for_my_account(self):
        """Test case for get_variation_for_my_account

        Variation  # noqa: E501
        """
        pass

    def test_parameters(self):
        """Test case for parameters

        'My Account' parameters  # noqa: E501
        """
        pass

    def test_predict_price(self):
        """Test case for predict_price

        Returns list of items and predicted price  # noqa: E501
        """
        pass

    def test_send_payment_error(self):
        """Test case for send_payment_error

        Sends payment error to server  # noqa: E501
        """
        pass

    def test_stop_account(self):
        """Test case for stop_account

        Stop billing  # noqa: E501
        """
        pass

    def test_update_billing_info(self):
        """Test case for update_billing_info

        Billing info  # noqa: E501
        """
        pass

    def test_update_payment_method(self):
        """Test case for update_payment_method

        Update payment method  # noqa: E501
        """
        pass

    def test_upgrade_plan(self):
        """Test case for upgrade_plan

        Change plan  # noqa: E501
        """
        pass

    def test_validate_billing_info_for_my_account(self):
        """Test case for validate_billing_info_for_my_account

        Test Billing info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
