# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.stats_api import StatsApi  # noqa: E501
from qu.crm.rest import ApiException


class TestStatsApi(unittest.TestCase):
    """StatsApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.stats_api.StatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_stats(self):
        """Test case for get_account_stats

        Account stats  # noqa: E501
        """
        pass

    def test_get_agents_stats(self):
        """Test case for get_agents_stats

        Agents stats for accounts with 10 or more agents  # noqa: E501
        """
        pass

    def test_get_sale_stats(self):
        """Test case for get_sale_stats

        Sale stats  # noqa: E501
        """
        pass

    def test_get_versions_stats(self):
        """Test case for get_versions_stats

        Versions stats  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
