# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import qu.crm
from qu.crm.models.summary_history_item import SummaryHistoryItem  # noqa: E501
from qu.crm.rest import ApiException

class TestSummaryHistoryItem(unittest.TestCase):
    """SummaryHistoryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SummaryHistoryItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SummaryHistoryItem`
        """
        model = qu.crm.models.summary_history_item.SummaryHistoryItem()  # noqa: E501
        if include_optional :
            return SummaryHistoryItem(
                order_number = '', 
                var_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                charged_invoices = [
                    qu.crm.models.summary_invoice.SummaryInvoice(
                        invoice_number = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        paid_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        price_billed = 1.337, 
                        currency = 'USD', )
                    ], 
                period = '1m', 
                plan_name = '', 
                price_usd = 1.337
            )
        else :
            return SummaryHistoryItem(
        )
        """

    def testSummaryHistoryItem(self):
        """Test SummaryHistoryItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
