# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import qu.crm
from qu.crm.models.refund import Refund  # noqa: E501
from qu.crm.rest import ApiException

class TestRefund(unittest.TestCase):
    """Refund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Refund
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Refund`
        """
        model = qu.crm.models.refund.Refund()  # noqa: E501
        if include_optional :
            return Refund(
                id = 56, 
                invoice_number = '', 
                amount = 1.337, 
                is_full_refund = True, 
                refunded_by = '', 
                refunded_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                note = ''
            )
        else :
            return Refund(
        )
        """

    def testRefund(self):
        """Test Refund"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
