# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.hack_api import HackApi  # noqa: E501
from qu.crm.rest import ApiException


class TestHackApi(unittest.TestCase):
    """HackApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.hack_api.HackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hack_dummy_payment_method(self):
        """Test case for hack_dummy_payment_method

        Set dummy payment method  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
