# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.minions_api import MinionsApi  # noqa: E501
from qu.crm.rest import ApiException


class TestMinionsApi(unittest.TestCase):
    """MinionsApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.minions_api.MinionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_minion(self):
        """Test case for add_new_minion

        Add new minion  # noqa: E501
        """
        pass

    def test_delete_minion(self):
        """Test case for delete_minion

        Delete minion  # noqa: E501
        """
        pass

    def test_edit_minion(self):
        """Test case for edit_minion

        Edit minion  # noqa: E501
        """
        pass

    def test_get_minion(self):
        """Test case for get_minion

        Minion  # noqa: E501
        """
        pass

    def test_get_minion_cluster_names(self):
        """Test case for get_minion_cluster_names

        Minion cluster names list  # noqa: E501
        """
        pass

    def test_get_minion_roles(self):
        """Test case for get_minion_roles

        Minion roles list  # noqa: E501
        """
        pass

    def test_get_minions(self):
        """Test case for get_minions

        Minions list  # noqa: E501
        """
        pass

    def test_re_sync_minion(self):
        """Test case for re_sync_minion

        Resync minion and set it up  # noqa: E501
        """
        pass

    def test_set_minion_down(self):
        """Test case for set_minion_down

        Set minion down  # noqa: E501
        """
        pass

    def test_set_minion_up(self):
        """Test case for set_minion_up

        Set minion up  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
