# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.attributes_api import AttributesApi  # noqa: E501
from qu.crm.rest import ApiException


class TestAttributesApi(unittest.TestCase):
    """AttributesApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.attributes_api.AttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attribute(self):
        """Test case for get_attribute

        Attribute  # noqa: E501
        """
        pass

    def test_get_attributes(self):
        """Test case for get_attributes

        Attribute list  # noqa: E501
        """
        pass

    def test_set_attribute(self):
        """Test case for set_attribute

        Attribute  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
