# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import qu.crm
from qu.crm.models.account_stats import AccountStats  # noqa: E501
from qu.crm.rest import ApiException

class TestAccountStats(unittest.TestCase):
    """AccountStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountStats`
        """
        model = qu.crm.models.account_stats.AccountStats()  # noqa: E501
        if include_optional :
            return AccountStats(
                today_new = 1.337, 
                today_new_paid = 1.337, 
                active = 1.337, 
                active_paid = 1.337, 
                agents = 1.337, 
                agents_paid = 1.337, 
                variations_active = None, 
                variations_agents = None
            )
        else :
            return AccountStats(
        )
        """

    def testAccountStats(self):
        """Test AccountStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
