# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import qu.crm
from qu.crm.models.billing_status import BillingStatus  # noqa: E501
from qu.crm.rest import ApiException

class TestBillingStatus(unittest.TestCase):
    """BillingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BillingStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingStatus`
        """
        model = qu.crm.models.billing_status.BillingStatus()  # noqa: E501
        if include_optional :
            return BillingStatus(
                status = 'N', 
                valid_to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                next_billing_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                billing_day = 56, 
                billing_period = '1m', 
                billing_period_start = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                billing_period_end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                errors = 56, 
                last_error_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                payment_compatible = True, 
                uses_legacy_billing = True
            )
        else :
            return BillingStatus(
        )
        """

    def testBillingStatus(self):
        """Test BillingStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
