# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.refunds_api import RefundsApi  # noqa: E501
from qu.crm.rest import ApiException


class TestRefundsApi(unittest.TestCase):
    """RefundsApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.refunds_api.RefundsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_refund(self):
        """Test case for get_refund

        Refund  # noqa: E501
        """
        pass

    def test_get_refunds(self):
        """Test case for get_refunds

        Refund list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
