# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import qu.crm
from qu.crm.api.variations_api import VariationsApi  # noqa: E501
from qu.crm.rest import ApiException


class TestVariationsApi(unittest.TestCase):
    """VariationsApi unit test stubs"""

    def setUp(self):
        self.api = qu.crm.api.variations_api.VariationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_variation_addons(self):
        """Test case for get_all_variation_addons

        Variations addons  # noqa: E501
        """
        pass

    def test_get_variation(self):
        """Test case for get_variation

        Variation  # noqa: E501
        """
        pass

    def test_get_variation_addons(self):
        """Test case for get_variation_addons

        Variations addons  # noqa: E501
        """
        pass

    def test_get_variations(self):
        """Test case for get_variations

        Variation list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
