# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import qu.crm
from qu.crm.models.invoice import Invoice  # noqa: E501
from qu.crm.rest import ApiException

class TestInvoice(unittest.TestCase):
    """Invoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Invoice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Invoice`
        """
        model = qu.crm.models.invoice.Invoice()  # noqa: E501
        if include_optional :
            return Invoice(
                subscription_id = '', 
                number = '', 
                refund_id = '', 
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                paid_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                price = 1.337, 
                price_billed = 1.337, 
                vat_rate = 1.337, 
                currency = 'USD', 
                customer = qu.crm.models.customer.Customer(
                    name = '', 
                    email = '', 
                    company = '', 
                    phone = '', 
                    address1 = '', 
                    address2 = '', 
                    city = '', 
                    state = '', 
                    country = '', 
                    zip = '', 
                    vat_id = '', 
                    ico_sk = '', 
                    dic_sk = '', ), 
                items = [
                    qu.crm.models.invoice_item.InvoiceItem(
                        type = '', 
                        price = 1.337, 
                        description = '', 
                        from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else :
            return Invoice(
        )
        """

    def testInvoice(self):
        """Test Invoice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
