# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, validator

class BillingParameters(BaseModel):
    """
    BillingParameters
    """
    billing_period: Optional[StrictStr] = None
    variation_id: Optional[StrictStr] = None
    addons: Optional[conlist(StrictStr)] = Field(None, description="addon codenames")
    coupon: Optional[StrictStr] = None
    __properties = ["billing_period", "variation_id", "addons", "coupon"]

    @validator('billing_period')
    def billing_period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('1m', '1y'):
            raise ValueError("must be one of enum values ('1m', '1y')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BillingParameters:
        """Create an instance of BillingParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BillingParameters:
        """Create an instance of BillingParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BillingParameters.parse_obj(obj)

        _obj = BillingParameters.parse_obj({
            "billing_period": obj.get("billing_period"),
            "variation_id": obj.get("variation_id"),
            "addons": obj.get("addons"),
            "coupon": obj.get("coupon")
        })
        return _obj

