# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr

class BillingMetric(BaseModel):
    """
    BillingMetric
    """
    name: Optional[StrictStr] = None
    amount_in_price: Optional[StrictInt] = None
    limit: Optional[StrictInt] = None
    unit_price: Optional[Union[StrictFloat, StrictInt]] = None
    unit_size: Optional[StrictInt] = None
    __properties = ["name", "amount_in_price", "limit", "unit_price", "unit_size"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BillingMetric:
        """Create an instance of BillingMetric from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BillingMetric:
        """Create an instance of BillingMetric from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BillingMetric.parse_obj(obj)

        _obj = BillingMetric.parse_obj({
            "name": obj.get("name"),
            "amount_in_price": obj.get("amount_in_price"),
            "limit": obj.get("limit"),
            "unit_price": obj.get("unit_price"),
            "unit_size": obj.get("unit_size")
        })
        return _obj

