# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, validator

class Discount(BaseModel):
    """
    Discount
    """
    id: Optional[StrictInt] = None
    subscription_id: StrictStr = Field(...)
    name: Optional[StrictStr] = None
    type: StrictStr = Field(...)
    value_type: StrictStr = Field(...)
    value: StrictInt = Field(...)
    note: Optional[StrictStr] = None
    created_by: Optional[StrictStr] = None
    date_created: Optional[StrictStr] = None
    expiration_type: Optional[StrictStr] = None
    days_valid: Optional[StrictStr] = None
    ended_by: Optional[StrictStr] = None
    date_ended: Optional[StrictStr] = None
    __properties = ["id", "subscription_id", "name", "type", "value_type", "value", "note", "created_by", "date_created", "expiration_type", "days_valid", "ended_by", "date_ended"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('one_time', 'current_plan', 'permanent'):
            raise ValueError("must be one of enum values ('one_time', 'current_plan', 'permanent')")
        return value

    @validator('value_type')
    def value_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('per_cent', 'constant'):
            raise ValueError("must be one of enum values ('per_cent', 'constant')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Discount:
        """Create an instance of Discount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                            "created_by",
                            "date_created",
                            "ended_by",
                            "date_ended",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Discount:
        """Create an instance of Discount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Discount.parse_obj(obj)

        _obj = Discount.parse_obj({
            "id": obj.get("id"),
            "subscription_id": obj.get("subscription_id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "value_type": obj.get("value_type"),
            "value": obj.get("value"),
            "note": obj.get("note"),
            "created_by": obj.get("created_by"),
            "date_created": obj.get("date_created"),
            "expiration_type": obj.get("expiration_type"),
            "days_valid": obj.get("days_valid"),
            "ended_by": obj.get("ended_by"),
            "date_ended": obj.get("date_ended")
        })
        return _obj

