# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr

class InstallProgress(BaseModel):
    """
    InstallProgress
    """
    account_status: Optional[StrictStr] = None
    progress: Optional[StrictInt] = None
    message: Optional[StrictStr] = None
    login_url: Optional[StrictStr] = None
    login_token: Optional[StrictStr] = None
    __properties = ["account_status", "progress", "message", "login_url", "login_token"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InstallProgress:
        """Create an instance of InstallProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InstallProgress:
        """Create an instance of InstallProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InstallProgress.parse_obj(obj)

        _obj = InstallProgress.parse_obj({
            "account_status": obj.get("account_status"),
            "progress": obj.get("progress"),
            "message": obj.get("message"),
            "login_url": obj.get("login_url"),
            "login_token": obj.get("login_token")
        })
        return _obj

