# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator

class MinionJob(BaseModel):
    """
    MinionJob
    """
    action_id: StrictStr = Field(...)
    minion_id: StrictStr = Field(...)
    created_at: Optional[datetime] = None
    salt_jid: Optional[StrictStr] = None
    scheduled_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    result: Optional[StrictStr] = Field(None, description="S - OK E - error R - running N - not scheduled")
    result_body: Optional[StrictStr] = None
    __properties = ["action_id", "minion_id", "created_at", "salt_jid", "scheduled_at", "finished_at", "result", "result_body"]

    @validator('result')
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('S', 'E', 'R', 'N'):
            raise ValueError("must be one of enum values ('S', 'E', 'R', 'N')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MinionJob:
        """Create an instance of MinionJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MinionJob:
        """Create an instance of MinionJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MinionJob.parse_obj(obj)

        _obj = MinionJob.parse_obj({
            "action_id": obj.get("action_id"),
            "minion_id": obj.get("minion_id"),
            "created_at": obj.get("created_at"),
            "salt_jid": obj.get("salt_jid"),
            "scheduled_at": obj.get("scheduled_at"),
            "finished_at": obj.get("finished_at"),
            "result": obj.get("result"),
            "result_body": obj.get("result_body")
        })
        return _obj

