# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr, validator

class PaymentProcessorType(BaseModel):
    """
    PaymentProcessorType
    """
    processor_type: Optional[StrictStr] = None
    token: Optional[StrictStr] = None
    init_token: Optional[StrictStr] = None
    braintree_merchant_account_id: Optional[StrictStr] = None
    __properties = ["processor_type", "token", "init_token", "braintree_merchant_account_id"]

    @validator('processor_type')
    def processor_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('Braintree', 'Stripe'):
            raise ValueError("must be one of enum values ('Braintree', 'Stripe')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PaymentProcessorType:
        """Create an instance of PaymentProcessorType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PaymentProcessorType:
        """Create an instance of PaymentProcessorType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PaymentProcessorType.parse_obj(obj)

        _obj = PaymentProcessorType.parse_obj({
            "processor_type": obj.get("processor_type"),
            "token": obj.get("token"),
            "init_token": obj.get("init_token"),
            "braintree_merchant_account_id": obj.get("braintree_merchant_account_id")
        })
        return _obj

