# coding: utf-8

"""
    CRM API

    This page contains complete API documentation for CRM software.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: support@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class ResellerSignup(BaseModel):
    """
    ResellerSignup
    """
    variation_id: StrictStr = Field(...)
    subdomain: StrictStr = Field(...)
    initial_name: StrictStr = Field(..., description="The name of initial application user")
    initial_email: StrictStr = Field(..., description="The email of initial application user")
    initial_pass: Optional[StrictStr] = Field(None, description="Password of initial application user")
    initial_language: Optional[StrictStr] = Field(None, description="Code of initial application language")
    initial_api_key: Optional[StrictStr] = Field(None, description="The initial application api key")
    __properties = ["variation_id", "subdomain", "initial_name", "initial_email", "initial_pass", "initial_language", "initial_api_key"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ResellerSignup:
        """Create an instance of ResellerSignup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ResellerSignup:
        """Create an instance of ResellerSignup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ResellerSignup.parse_obj(obj)

        _obj = ResellerSignup.parse_obj({
            "variation_id": obj.get("variation_id"),
            "subdomain": obj.get("subdomain"),
            "initial_name": obj.get("initial_name"),
            "initial_email": obj.get("initial_email"),
            "initial_pass": obj.get("initial_pass"),
            "initial_language": obj.get("initial_language"),
            "initial_api_key": obj.get("initial_api_key")
        })
        return _obj

